# site name
prefixName: Robin
siteName: Wang
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://www.codersart.cn/
description: 生活要有仪式感，认真生活!
cdn: https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎你的到来
lazyloadImg: https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    技术: {path: /categories/技术/, fa: fa-code },
    生活: {path: /categories/生活/, fa: fa-file-text-o },
    资源: {path: /categories/资源/, fa: fa-cloud-download },
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book },
    艺术: {path: /categories/艺术/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    转载: {path: /categories/转载/, fa: fa-book },
    书单: {path: /tags/阅读/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  语言: { path: javascript:;, fa: fa-archive faa-shake, submenus: {
    JS: {path: /tags/JavaScript/},
    TS: {path: /tags/TypeScript/},
    ES6: {path: /tags/ECMAScript/},
    Node: {path: /tags/Nodejs/},
    Java: {path: /tags/Java/},
    Pyhton: {path: /tags/Pyhton/},
    Dart: {path: /tags/Dart/},
  } }
  框架: { path: javascript:;, fa: fa-archive faa-shake, submenus: {
    vue:{path: /tags/vue/},
    ng:{path: /tags/angular/},
    react:{path: /tags/react/},
    ionic:{path: /tags/ionic/},
    flutter:{path: /tags/flutter/},
    Boot:{path: /tags/Boot/},
    WX:{path: /tags/weixin/},
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    # 我？: {path: /about/, fa: fa-meetup},
    # 主题: {path: /theme-sakura/, fa: iconfo/nt icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/RobinWM/cdn@2.0/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://www.github.com/RobinWM, title: Github, desc: 博主的Github主页, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 代码艺术之家, desc: 技术分享, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 10/22/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/RobinWM, img: /img/social/github.png}
  sina: {url: https://weibo.com/u/2657334007/home?wvr=5, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=1415574587, img: /img/social/wangyiyun.png}
  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: https://weibo.com/u/2657334007/home?wvr=5, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wx.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/RobinWangM
  alipay: /img/custom/donate/AliPay.png
  wechat: /img/custom/donate/WXPay.png
  wechatSQ: /img/custom/donate/WXPay.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  id: 614012016
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: random
  preload: auto
  volume: 0.3
  mutex: true

# Valine
valine: true
v_appId: WD4BEpJn9J3BP3SGI9Ue4GAc-gzGzoHsz
v_appKey: C9PkgmAoeXogDvSgoeyp3qnI

